- name: git clone Covenant
  git:
    repo: https://github.com/cobbr/Covenant.git
    dest: "{{ covenant_dir }}"
    update: no
    force: yes
    recursive: true
  become: yes

- name: build covenant image
  docker_image:
    name: covenant
    build:
      path: "{{ covenant_dir }}/Covenant"
      pull: yes
    source: build

- name: start Covenant container
  docker_container:
    name: covenant
    image: covenant:latest
    volumes: "{{ covenant_dir }}/Covenant/Data:/app/Data"
    ports:
      - "7443:7443"
      - "8080:80"
      - "8443:443"
